language: node_js
node_js:
  - '4'
before_script:
  - 'npm install -g gulp'
  - 'npm install'
script:
  - 'gulp ci'
notifications:
  email: false
  slack: $SLACK_TOKEN

# Do full build before a deploy (including copying of node and bower files).
before_deploy:
  - 'gulp'
deploy:
  - provider: gcs
    access_key_id: $GCS_ACCESS_KEY
    secret_access_key: $GCS_SECRET_ACCESS_KEY
    bucket: "static.joulia.io"
    skip_cleanup: true
    local_dir: dist
    acl: public-read
    cache_control: "private, max-age=0, no-transform"
