language: node_js
node_js:
  - '4'
before_script:
  - 'npm install -g bower'
  - 'npm install -g gulp'
  - 'bower install'
before_deploy:
  - 'gulp'
notifications:
  email: false
  slack: $SLACK_TOKEN
deploy:
  - provider: gcs
    access_key_id: $GCS_ACCESS_KEY
    secret_access_key: $GCS_SECRET_ACCESS_KEY
    bucket: "static.joulia.io"
    skip_cleanup: true
    local_dir: dist
    acl: public-read
    cache_control: "private, max-age=0, no-transform"
