language: node_js
node_js:
  - '4.4.3'
before_script:
  - 'npm install -g bower'
  - 'npm install -g grunt-cli'
  - 'bower install'
before_deploy:
  - 'grunt travisbuild'
notifications:
  email: false
  slack: $SLACK_TOKEN
deploy:
  - provider: s3
    access_key_id: $S3_ACCESS_KEY
    secret_access_key: $S3_SECRET_ACCESS_KEY
    bucket: "joulia-webclient"
    skip_cleanup: true
    local_dir: dist
    acl: public_read
  - provider: gcs
    access_key_id: $GCS_ACCESS_KEY
    secret_access_key: $GCS_SECRET_ACCESS_KEY
    bucket: "joulia-webclient"
    skip_cleanup: true
    local_dir: dist
    acl: public-read
